name: Packer AMI Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Packer
      uses: hashicorp/setup-packer@main
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Install Chef
      run: |
        curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk
    
    - name: Packer inititalization
      run: packer init packer-template.pkr.hcl
      
    - name: Validate Packer Template
      run: packer validate packer-template.pkr.hcl
    
    - name: Build Packer Image
      run: packer build packer-template.pkr.hcl
